# Generated by Django 4.0 on 2022-04-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('uuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinateSystem', models.CharField(max_length=100)),
                ('ellipsoid', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Geometrie',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('frameId', models.CharField(max_length=100)),
                ('stamp', models.CharField(max_length=100)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bedApi.bed')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='geolocation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bedApi.geolocation'),
        ),
    ]
